baseURL = "https://yerkoescalona.github.io/"
title = "Yerko Escalona"
themesDir = "./themes"
theme = "m10c"
paginate = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Yerko Escalona"
  description = "Ser vivo. Animal con cabeza, tronco y extremidades. Habitante del planeta Tierra. Persona humana. ... y  otras etiquetas, producto de delirios mentales humanos."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/yerkoescalona"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/yerkoescalona"
  [[params.social]]
    icon = "facebook"
    name = "Faecebook"
    url = "https://www.facebook.com/y33333rk0000033333sc4l000000n44444444/"
  [[params.social]]
    icon = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/yerkoescalona/"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
