baseURL = "/"
languageCode = "en-us"
title = "Yerko Escalona"
theme = "rusty-typewriter"
pluralizelisttitles = false

[services]
    [services.googleAnalytics]
        ID = "G-XC6T0LK1MF"

[pagination]
    pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    series = 'series'
    tags = 'tags'

[[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 1

[[menus.main]]
    name = "Publications"
    pageRef = "/publications"
    weight = 2

[[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 3

[params]
    description = "Científico tratando de reinventarse..."

    [params.author]
        name = "Yerko Escalona"

    [params.links]
        theme = "https://github.com/math-queiroz/rusty-typewriter"
        hugo = "https://gohugo.io/"

    [params.rtwt]
        countPageItems = 10

        [params.rtwt.home]
            showBio = true
            showAuthorImg = true

        [params.rtwt.side.home]
            taxonomies = ['tags', 'series']
            countTaxonomy = 5

        [params.rtwt.side.single]
            showDetails = true
            showTableOfContents = true
            showRelated = true
            countRelated = 3

# build search index
[outputFormats]
    [outputFormats.SearchIndex]
        mediaType = "application/json"
        baseName = "searchindex"
        isPlainText = true
        notAlternative = true

[mediaTypes]
    [mediaTypes."application/json"]
        suffixes = ["json"]

[outputs]
    home = ["HTML", "RSS", "SearchIndex"]
